#!/bin/bash

echo ""
echo -e "\e[1;34m ---------------- BUILD ---------------- \e[0;37m"
echo ""

make

echo ""
echo -e "\e[1;32m ---------------- OUTPUT ---------------- \e[0;37m"
echo ""

echo "execution my_hunter"
./my_hunter
echo "my_hunter executed"
#echo "nothing here"

echo ""
echo -e "\e[1;33m --------------- VALGRIND --------------- \e[0;37m"
echo ""

valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all -s ./my_hunter
echo "nothing here"

echo ""
echo -e "\e[1;35m ---------------- CLEAN ---------------- \e[0;37m"
echo ""

make fclean > /dev/null

echo -e "\e[1;32mclean done\e[0;37m"

echo ""
